@startuml functional_example

/'
https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/06.01-define-an-application-protocol/03-solution/01-guess-the-number-game/README.md
'/

actor Bob as Player1 #PaleGreen
Participant Server #OrangeRed
actor Alice as Player2 #PaleTurquoise

autonumber

note across : Connection is already established


group Connection with one player lost
    Player1 -> Server : QUIT
    Server -> Player2 : LOST Bob
end
...

@endum